### ISSUE TITLE
editor background color

### ISSUE THREAD

**Issue by rmiaziozinio** [djredfern/Squirrel-SQL#1]
If I understood correctly, this changes 01edb13c371b24d768528570519a998073b8b220 should make editors background color same as syntax whitespace color, I am ok? I cannot make it work somehow. Does it work?

**Comment by rmiaziozinio** [comment]
I managed to make it work. Great. Thank you!

**Comment by djredfern** [comment]
That's good news... Gerd Wagner has also taken the code and put it in the latest official Squirrel Snapshot.

**Comment by copperschnack** [comment]
Hi. I tried L&F "Substance" with Skin "RavenGraphiteSkin" in versions 3.7 and snapshot-20150923_2101. The editor background stays light and does not switch to whitespace color. I cannot find a setting to switch this. @rmiaziozinio, do you recall how you made it work? Thanks.

**Comment by djredfern** [comment]
Hello:

It looks like the latest version of Squirrel uses the latest Rsyntax which 
keeps background colors from working.. Below is from the enhancements 
page. When I have a minute I'll try looking at what changed...


Upgraded to latest RSyntax version (2.5.6).


  The new version has a clipboard history which is accessible through ctrl 
shift v.


  A little drawback of the new version is that background colors are not 
supported in syntax styles.



 
Regards,

Duane

**Comment by djredfern** [comment]
I just tried the latest and my colors are working... maybe they fixed 
it...
